USE [BAMTS_DB]
GO
/****** Object:  StoredProcedure [dbo].[P_Get_OrderList_ForLegacyExcel]    Script Date: 2022/06/16 15:13:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_Import_OrderList_ForLegacyExcel]
(
	@userID varchar(32),
	@recList S_Get_OrderList_ForLegacyExcel readonly
)
AS
BEGIN
declare @NowTime					datetime = getdate()
declare @Message					nvarchar(2048) = ''

declare @STATUS int
declare @ODR_PERIOD int
declare @ODR_CATEGORY varchar(8)
declare @ODR_MONTH varchar(2)
declare @ODR_SEQ int
declare @DLV_SUBMIT_DATE datetime
declare @DLV_DEADLINE_DATE datetime
declare @DLVREP_SUBMIT_DATE datetime
declare @CMPREP_ISSUE_DATE datetime
declare @CMPREP_DEADLINE_DATE datetime
declare @CMPMAIL_ISSUE_DATE datetime
declare @CMPMAIL_DEADLINE_DATE datetime
declare @CNST_MANAGER_ID varchar(32)
declare @CNST_MANAGER_NAME nvarchar(64)
declare @TYPE int
declare @REV_ISSUE_DATE datetime
declare @REV_NO int
declare @EST_ISSUE_DATE datetime
declare @CUSTOMER_ID int
declare @CUSTOMER_NAME nvarchar(256)
declare @ODR_NAME nvarchar(256)
declare @CNST_START_DATE datetime
declare @CNST_END_DATE datetime
declare @OPEN_DATE datetime
declare @NOTE nvarchar(512)
declare @ESTREQ_NO_1 varchar(16)
declare @ESTREQ_NO_2 varchar(16)
declare @PRODUCT_NO varchar(16)
declare @REQ_DATE datetime
declare @REQ_NO varchar(16)
declare @ODR_DATE datetime
declare @ODR_NO varchar(16)
declare @ACCEPT_DATE datetime
declare @ACCEPT_MONTH datetime
declare @PAYMENT_MONTH datetime
declare @ANS_NET_PRICE int
declare @ANS_TAX_PRICE int
declare @CNST_NET_PRICE int
declare @CNST_TAX_PRICE int
declare @STUP_NET_PRICE int
declare @STUP_TAX_PRICE int
declare @ASSOCIATE_ID_1 int
declare @ASSOCIATE_NAME_1 nvarchar(256)
declare @WORKER_NAME_1 nvarchar(32)
declare @NET_PRICE_1 int
declare @TAX_PRICE_1 int
declare @PAYMENT_MONTH_1 datetime
declare @ASSOCIATE_ID_2 int
declare @ASSOCIATE_NAME_2 nvarchar(256)
declare @WORKER_NAME_2 nvarchar(32)
declare @NET_PRICE_2 int
declare @TAX_PRICE_2 int
declare @PAYMENT_MONTH_2 datetime
declare @ASSOCIATE_ID_3 int
declare @ASSOCIATE_NAME_3 nvarchar(256)
declare @WORKER_NAME_3 nvarchar(32)
declare @NET_PRICE_3 int
declare @TAX_PRICE_3 int
declare @PAYMENT_MONTH_3 datetime
declare curTargets cursor for select [STATUS],[ODR_PERIOD],[ODR_CATEGORY],[ODR_MONTH],[ODR_SEQ],[DLV_SUBMIT_DATE],[DLV_DEADLINE_DATE],[DLVREP_SUBMIT_DATE],[CMPREP_ISSUE_DATE],[CMPREP_DEADLINE_DATE],[CMPMAIL_ISSUE_DATE],[CMPMAIL_DEADLINE_DATE],[CNST_MANAGER_ID],[CNST_MANAGER_NAME],[TYPE],[REV_ISSUE_DATE],[REV_NO],[EST_ISSUE_DATE],[CUSTOMER_ID],[CUSTOMER_NAME],[ODR_NAME],[CNST_START_DATE],[CNST_END_DATE],[OPEN_DATE],[NOTE],[ESTREQ_NO_1],[ESTREQ_NO_2],[PRODUCT_NO],[REQ_DATE],[REQ_NO],[ODR_DATE],[ODR_NO],[ACCEPT_DATE],[ACCEPT_MONTH],[PAYMENT_MONTH],[ANS_NET_PRICE],[ANS_TAX_PRICE],[CNST_NET_PRICE],[CNST_TAX_PRICE],[STUP_NET_PRICE],[STUP_TAX_PRICE],[ASSOCIATE_ID_1],[ASSOCIATE_NAME_1],[WORKER_NAME_1],[NET_PRICE_1],[TAX_PRICE_1],[PAYMENT_MONTH_1],[ASSOCIATE_ID_2],[ASSOCIATE_NAME_2],[WORKER_NAME_2],[NET_PRICE_2],[TAX_PRICE_2],[PAYMENT_MONTH_2],[ASSOCIATE_ID_3],[ASSOCIATE_NAME_3],[WORKER_NAME_3],[NET_PRICE_3],[TAX_PRICE_3],[PAYMENT_MONTH_3] from @recList
begin try
	delete from X_EMPLOYEE
	open curTargets
	fetch next from curTargets into @STATUS,@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,@DLV_SUBMIT_DATE,@DLV_DEADLINE_DATE,@DLVREP_SUBMIT_DATE,@CMPREP_ISSUE_DATE,@CMPREP_DEADLINE_DATE,@CMPMAIL_ISSUE_DATE,@CMPMAIL_DEADLINE_DATE,@CNST_MANAGER_ID,@CNST_MANAGER_NAME,@TYPE,@REV_ISSUE_DATE,@REV_NO,@EST_ISSUE_DATE,@CUSTOMER_ID,@CUSTOMER_NAME,@ODR_NAME,@CNST_START_DATE,@CNST_END_DATE,@OPEN_DATE,@NOTE,@ESTREQ_NO_1,@ESTREQ_NO_2,@PRODUCT_NO,@REQ_DATE,@REQ_NO,@ODR_DATE,@ODR_NO,@ACCEPT_DATE,@ACCEPT_MONTH,@PAYMENT_MONTH,@ANS_NET_PRICE,@ANS_TAX_PRICE,@CNST_NET_PRICE,@CNST_TAX_PRICE,@STUP_NET_PRICE,@STUP_TAX_PRICE,@ASSOCIATE_ID_1,@ASSOCIATE_NAME_1,@WORKER_NAME_1,@NET_PRICE_1,@TAX_PRICE_1,@PAYMENT_MONTH_1,@ASSOCIATE_ID_2,@ASSOCIATE_NAME_2,@WORKER_NAME_2,@NET_PRICE_2,@TAX_PRICE_2,@PAYMENT_MONTH_2,@ASSOCIATE_ID_3,@ASSOCIATE_NAME_3,@WORKER_NAME_3,@NET_PRICE_3,@TAX_PRICE_3,@PAYMENT_MONTH_3

	while (@@fetch_status = 0)
	begin
		delete from T_ORDERS where (ODR_PERIOD = @ODR_PERIOD) and (ODR_CATEGORY = @ODR_CATEGORY) and (ODR_MONTH = @ODR_MONTH) and (ODR_SEQ = @ODR_SEQ)
		delete from T_ORDER_SALES where (ODR_PERIOD = @ODR_PERIOD) and (ODR_CATEGORY = @ODR_CATEGORY) and (ODR_MONTH = @ODR_MONTH) and (ODR_SEQ = @ODR_SEQ)
		delete from T_ORDER_ESTIMATE where (ODR_PERIOD = @ODR_PERIOD) and (ODR_CATEGORY = @ODR_CATEGORY) and (ODR_MONTH = @ODR_MONTH) and (ODR_SEQ = @ODR_SEQ)
		delete from T_ORDER_COST where (ODR_PERIOD = @ODR_PERIOD) and (ODR_CATEGORY = @ODR_CATEGORY) and (ODR_MONTH = @ODR_MONTH) and (ODR_SEQ = @ODR_SEQ)

		select @CNST_MANAGER_ID = STAFF_ID from T_STAFF where (STAFF_NAME like '%' + @CNST_MANAGER_NAME + '%')
		select @CUSTOMER_ID = CUSTOMER_ID from T_CUSTOMER where (CUSTOMER_NAME like '%' + @CUSTOMER_NAME + '%')
		select @ASSOCIATE_ID_1 = ASSOCIATE_ID from T_ASSOCIATE where (ASSOCIATE_NAME like '%' + @ASSOCIATE_NAME_1 + '%')
		select @ASSOCIATE_ID_2 = ASSOCIATE_ID from T_ASSOCIATE where (ASSOCIATE_NAME like '%' + @ASSOCIATE_NAME_2 + '%')
		select @ASSOCIATE_ID_3 = ASSOCIATE_ID from T_ASSOCIATE where (ASSOCIATE_NAME like '%' + @ASSOCIATE_NAME_3 + '%')

		insert into T_ORDERS ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,[STATUS], DLV_SUBMIT_DATE, DLV_DEADLINE_DATE, DLVREP_SUBMIT_DATE, CMPREP_ISSUE_DATE, CMPREP_DEADLINE_DATE, CMPMAIL_ISSUE_DATE, CMPMAIL_DEADLINE_DATE, CNST_MANAGER   ,[TYPE], REV_ISSUE_DATE, REV_NO, EST_ISSUE_DATE, CUSTOMER_ID, ODR_NAME, CNST_START_DATE, CNST_END_DATE, OPEN_DATE, NOTE,UPD_TIME,UPD_USER)
					  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,@STATUS ,@DLV_SUBMIT_DATE,@DLV_DEADLINE_DATE,@DLVREP_SUBMIT_DATE,@CMPREP_ISSUE_DATE,@CMPREP_DEADLINE_DATE,@CMPMAIL_ISSUE_DATE,@CMPMAIL_DEADLINE_DATE,@CNST_MANAGER_ID,@TYPE ,@REV_ISSUE_DATE,@REV_NO,@EST_ISSUE_DATE,@CUSTOMER_ID,@ODR_NAME,@CNST_START_DATE,@CNST_END_DATE,@OPEN_DATE,@NOTE,@NowTime, @userID)

		insert into T_ORDER_SALES ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO, ESTREQ_NO_1, ESTREQ_NO_2, PRODUCT_NO, REQ_DATE, REQ_NO, ODR_DATE, ODR_NO, ACCEPT_DATE, ACCEPT_MONTH, PAYMENT_MONTH, ANS_NET_PRICE, ANS_TAX_PRICE,UPD_TIME,UPD_USER)
						   values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      0,@ESTREQ_NO_1,@ESTREQ_NO_2,@PRODUCT_NO,@REQ_DATE,@REQ_NO,@ODR_DATE,@ODR_NO,@ACCEPT_DATE,@ACCEPT_MONTH,@PAYMENT_MONTH,@ANS_NET_PRICE,@ANS_TAX_PRICE,@NowTime, @userID)

		insert into T_ORDER_ESTIMATE ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO,ITEM_TYPE,TITLE_NAME,      NET_PRICE,      TAX_PRICE,UPD_TIME,UPD_USER)
							  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      0,        0,        '',@CNST_NET_PRICE,@CNST_TAX_PRICE,@NowTime, @userID)
		insert into T_ORDER_ESTIMATE ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO,ITEM_TYPE,TITLE_NAME,      NET_PRICE,      TAX_PRICE,UPD_TIME,UPD_USER)
							  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      1,        1,        '',@STUP_NET_PRICE,@STUP_TAX_PRICE,@NowTime, @userID)

		insert into T_ORDER_COST ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO, ASSOCIATE_ID  , WORKER_NAME  ,   NET_PRICE,   TAX_PRICE, PAYMENT_MONTH  ,UPD_TIME,UPD_USER)
						  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      0,@ASSOCIATE_ID_1,@WORKER_NAME_1,@NET_PRICE_1,@TAX_PRICE_1,@PAYMENT_MONTH_1,@NowTime, @userID)
		insert into T_ORDER_COST ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO, ASSOCIATE_ID  , WORKER_NAME  ,   NET_PRICE,   TAX_PRICE, PAYMENT_MONTH  ,UPD_TIME,UPD_USER)
						  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      1,@ASSOCIATE_ID_2,@WORKER_NAME_2,@NET_PRICE_2,@TAX_PRICE_2,@PAYMENT_MONTH_2,@NowTime, @userID)
		insert into T_ORDER_COST ( ODR_PERIOD, ODR_CATEGORY, ODR_MONTH, ODR_SEQ,ITEM_NO, ASSOCIATE_ID  , WORKER_NAME  ,   NET_PRICE,   TAX_PRICE, PAYMENT_MONTH  ,UPD_TIME,UPD_USER)
						  values (@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,      2,@ASSOCIATE_ID_3,@WORKER_NAME_3,@NET_PRICE_3,@TAX_PRICE_3,@PAYMENT_MONTH_3,@NowTime, @userID)
		fetch next from curTargets into @STATUS,@ODR_PERIOD,@ODR_CATEGORY,@ODR_MONTH,@ODR_SEQ,@DLV_SUBMIT_DATE,@DLV_DEADLINE_DATE,@DLVREP_SUBMIT_DATE,@CMPREP_ISSUE_DATE,@CMPREP_DEADLINE_DATE,@CMPMAIL_ISSUE_DATE,@CMPMAIL_DEADLINE_DATE,@CNST_MANAGER_ID,@CNST_MANAGER_NAME,@TYPE,@REV_ISSUE_DATE,@REV_NO,@EST_ISSUE_DATE,@CUSTOMER_ID,@CUSTOMER_NAME,@ODR_NAME,@CNST_START_DATE,@CNST_END_DATE,@OPEN_DATE,@NOTE,@ESTREQ_NO_1,@ESTREQ_NO_2,@PRODUCT_NO,@REQ_DATE,@REQ_NO,@ODR_DATE,@ODR_NO,@ACCEPT_DATE,@ACCEPT_MONTH,@PAYMENT_MONTH,@ANS_NET_PRICE,@ANS_TAX_PRICE,@CNST_NET_PRICE,@CNST_TAX_PRICE,@STUP_NET_PRICE,@STUP_TAX_PRICE,@ASSOCIATE_ID_1,@ASSOCIATE_NAME_1,@WORKER_NAME_1,@NET_PRICE_1,@TAX_PRICE_1,@PAYMENT_MONTH_1,@ASSOCIATE_ID_2,@ASSOCIATE_NAME_2,@WORKER_NAME_2,@NET_PRICE_2,@TAX_PRICE_2,@PAYMENT_MONTH_2,@ASSOCIATE_ID_3,@ASSOCIATE_NAME_3,@WORKER_NAME_3,@NET_PRICE_3,@TAX_PRICE_3,@PAYMENT_MONTH_3
	end
	close curTargets
	deallocate curTargets
end try
begin catch
	set @Message = N'ApplicationError:[P_Get_OrderList_ForLegacyExcel]にてエラーが発生しました。[' + STR(ERROR_NUMBER()) + ']:' + ERROR_MESSAGE() + ' <' + ERROR_PROCEDURE() + '>(Line:' + STR(ERROR_LINE()) + ')'
	EXEC xp_logevent 90001, @Message, error 
end catch

select @Message as RESULT_MESSAGE

END

