USE [BAMTS_DB]
GO

/****** Object:  UserDefinedTableType [dbo].[S_Get_OrderList_ForLegacyExcel]    Script Date: 2022/06/16 15:15:45 ******/
CREATE TYPE [dbo].[S_Get_OrderList_ForLegacyExcel] AS TABLE(
	[STATUS] [int] NULL,
	[ODR_PERIOD] [int] NULL,
	[ODR_CATEGORY] [varchar](8) NULL,
	[ODR_MONTH] [varchar](2) NULL,
	[ODR_SEQ] [int] NULL,
	[DLV_SUBMIT_DATE] [datetime] NULL,
	[DLV_DEADLINE_DATE] [datetime] NULL,
	[DLVREP_SUBMIT_DATE] [datetime] NULL,
	[CMPREP_ISSUE_DATE] [datetime] NULL,
	[CMPREP_DEADLINE_DATE] [datetime] NULL,
	[CMPMAIL_ISSUE_DATE] [datetime] NULL,
	[CMPMAIL_DEADLINE_DATE] [datetime] NULL,
	[CNST_MANAGER_ID] [varchar](32) NULL,
	[CNST_MANAGER_NAME] [nvarchar](64) NULL,
	[TYPE] [int] NULL,
	[REV_ISSUE_DATE] [datetime] NULL,
	[REV_NO] [int] NULL,
	[EST_ISSUE_DATE] [datetime] NULL,
	[CUSTOMER_ID] [int] NULL,
	[CUSTOMER_NAME] [nvarchar](256) NULL,
	[ODR_NAME] [nvarchar](256) NULL,
	[CNST_START_DATE] [datetime] NULL,
	[CNST_END_DATE] [datetime] NULL,
	[OPEN_DATE] [datetime] NULL,
	[NOTE] [nvarchar](512) NULL,
	[ESTREQ_NO_1] [varchar](16) NULL,
	[ESTREQ_NO_2] [varchar](16) NULL,
	[PRODUCT_NO] [varchar](16) NULL,
	[REQ_DATE] [datetime] NULL,
	[REQ_NO] [varchar](16) NULL,
	[ODR_DATE] [datetime] NULL,
	[ODR_NO] [varchar](16) NULL,
	[ACCEPT_DATE] [datetime] NULL,
	[ACCEPT_MONTH] [datetime] NULL,
	[PAYMENT_MONTH] [datetime] NULL,
	[ANS_NET_PRICE] [int] NULL,
	[ANS_TAX_PRICE] [int] NULL,
	[CNST_NET_PRICE] [int] NULL,
	[CNST_TAX_PRICE] [int] NULL,
	[STUP_NET_PRICE] [int] NULL,
	[STUP_TAX_PRICE] [int] NULL,
	[ASSOCIATE_ID_1] [int] NOT NULL,
	[ASSOCIATE_NAME_1] [nvarchar](256) NULL,
	[WORKER_NAME_1] [nvarchar](32) NULL,
	[NET_PRICE_1] [int] NULL,
	[TAX_PRICE_1] [int] NULL,
	[PAYMENT_MONTH_1] [datetime] NULL,
	[ASSOCIATE_ID_2] [int] NOT NULL,
	[ASSOCIATE_NAME_2] [nvarchar](256) NULL,
	[WORKER_NAME_2] [nvarchar](32) NULL,
	[NET_PRICE_2] [int] NULL,
	[TAX_PRICE_2] [int] NULL,
	[PAYMENT_MONTH_2] [datetime] NULL,
	[ASSOCIATE_ID_3] [int] NOT NULL,
	[ASSOCIATE_NAME_3] [nvarchar](256) NULL,
	[WORKER_NAME_3] [nvarchar](32) NULL,
	[NET_PRICE_3] [int] NULL,
	[TAX_PRICE_3] [int] NULL,
	[PAYMENT_MONTH_3] [datetime] NULL
)
GO


