USE [BAMTS_DB]
GO

/****** Object:  View [dbo].[V_ORDER_LIST_FOR_EXCEL_P1]    Script Date: 2022/06/15 15:46:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--DROP VIEW [dbo].[V_ORDER_LIST_FOR_EXCEL_P1]
--go

CREATE VIEW [dbo].[V_ORDER_LIST_FOR_EXCEL_P1] as 
	select
		 ODR.[STATUS] as STATUS
		,ODR.ODR_PERIOD
		,ODR.ODR_CATEGORY
		,ODR.ODR_MONTH
		,ODR.ODR_SEQ
		,ODR.DLV_SUBMIT_DATE
		,ODR.DLV_DEADLINE_DATE
		,ODR.DLVREP_SUBMIT_DATE
		,ODR.CMPREP_ISSUE_DATE
		,ODR.CMPREP_DEADLINE_DATE
		,ODR.CMPMAIL_ISSUE_DATE
		,ODR.CMPMAIL_DEADLINE_DATE
		,ODR.CNST_MANAGER as CNST_MANAGER_ID
		,STF.STAFF_NAME as CNST_MANAGER_NAME
		,ODR.[TYPE] as TYPE
		,ODR.REV_ISSUE_DATE
		,ODR.REV_NO
		,ODR.EST_ISSUE_DATE
		,ODR.CUSTOMER_ID
		,CUS.CUSTOMER_NAME
		,ODR.ODR_NAME
		,ODR.CNST_START_DATE
		,ODR.CNST_END_DATE
		,ODR.OPEN_DATE
		,ODR.NOTE
		,SAL.ESTREQ_NO_1
		,SAL.ESTREQ_NO_2
		,SAL.PRODUCT_NO
		,SAL.REQ_DATE
		,SAL.REQ_NO
		,SAL.ODR_DATE
		,SAL.ODR_NO
		,SAL.ACCEPT_DATE
		,SAL.ACCEPT_MONTH
		,SAL.PAYMENT_MONTH
		,SAL.ANS_NET_PRICE
		,SAL.ANS_TAX_PRICE
		,max(case when (EST.ITEM_TYPE = 0) then EST.NET_PRICE else null end) as CNST_NET_PRICE
		,max(case when (EST.ITEM_TYPE = 0) then EST.TAX_PRICE else null end) as CNST_TAX_PRICE
		,max(case when (EST.ITEM_TYPE = 1) then EST.NET_PRICE else null end) as STUP_NET_PRICE
		,max(case when (EST.ITEM_TYPE = 1) then EST.TAX_PRICE else null end) as STUP_TAX_PRICE
		,max(case when (CST.ITEM_NO = 0) then CST.ASSOCIATE_ID else null end) as ASSOCIATE_ID_1
		,max(case when (CST.ITEM_NO = 0) then ASO.ASSOCIATE_NAME else null end) as ASSOCIATE_NAME_1
		,max(case when (CST.ITEM_NO = 0) then CST.WORKER_NAME else null end) as WORKER_NAME_1
		,max(case when (CST.ITEM_NO = 0) then CST.NET_PRICE else null end) as NET_PRICE_1
		,max(case when (CST.ITEM_NO = 0) then CST.TAX_PRICE else null end) as TAX_PRICE_1
		,max(case when (CST.ITEM_NO = 0) then CST.PAYMENT_MONTH else null end) as PAYMENT_MONTH_1
		,max(case when (CST.ITEM_NO = 1) then CST.ASSOCIATE_ID else null end) as ASSOCIATE_ID_2
		,max(case when (CST.ITEM_NO = 1) then ASO.ASSOCIATE_NAME else null end) as ASSOCIATE_NAME_2
		,max(case when (CST.ITEM_NO = 1) then CST.WORKER_NAME else null end) as WORKER_NAME_2
		,max(case when (CST.ITEM_NO = 1) then CST.NET_PRICE else null end) as NET_PRICE_2
		,max(case when (CST.ITEM_NO = 1) then CST.TAX_PRICE else null end) as TAX_PRICE_2
		,max(case when (CST.ITEM_NO = 1) then CST.PAYMENT_MONTH else null end) as PAYMENT_MONTH_2
		,max(case when (CST.ITEM_NO = 2) then CST.ASSOCIATE_ID else null end) as ASSOCIATE_ID_3
		,max(case when (CST.ITEM_NO = 2) then ASO.ASSOCIATE_NAME else null end) as ASSOCIATE_NAME_3
		,max(case when (CST.ITEM_NO = 2) then CST.WORKER_NAME else null end) as WORKER_NAME_3
		,max(case when (CST.ITEM_NO = 2) then CST.NET_PRICE else null end) as NET_PRICE_3
		,max(case when (CST.ITEM_NO = 2) then CST.TAX_PRICE else null end) as TAX_PRICE_3
		,max(case when (CST.ITEM_NO = 2) then CST.PAYMENT_MONTH else null end) as PAYMENT_MONTH_3
	from 
		T_ORDERS as ODR
		left outer join T_ORDER_ESTIMATE as EST on (ODR.ODR_PERIOD = EST.ODR_PERIOD) and (ODR.ODR_CATEGORY = EST.ODR_CATEGORY) and (ODR.ODR_MONTH = EST.ODR_MONTH) and (ODR.ODR_SEQ = EST.ODR_SEQ) and (EST.ITEM_NO in (0, 1))
		left outer join T_ORDER_SALES as SAL on (ODR.ODR_PERIOD = SAL.ODR_PERIOD) and (ODR.ODR_CATEGORY = SAL.ODR_CATEGORY) and (ODR.ODR_MONTH = SAL.ODR_MONTH) and (ODR.ODR_SEQ = SAL.ODR_SEQ) and (SAL.ITEM_NO = 0)
		left outer join T_ORDER_COST as CST on (ODR.ODR_PERIOD = CST.ODR_PERIOD) and (ODR.ODR_CATEGORY = CST.ODR_CATEGORY) and (ODR.ODR_MONTH = CST.ODR_MONTH) and (ODR.ODR_SEQ = CST.ODR_SEQ) and (CST.ITEM_NO in (0, 1, 2))
		left outer join T_STAFF as STF on (ODR.CNST_MANAGER = STF.STAFF_ID)
		left outer join T_ASSOCIATE as ASO on (CST.ASSOCIATE_ID = ASO.ASSOCIATE_ID)
		left outer join T_CUSTOMER as CUS on (ODR.CUSTOMER_ID = CUS.CUSTOMER_ID)
	group by 
		 ODR.[STATUS]
		,ODR.ODR_PERIOD
		,ODR.ODR_CATEGORY
		,ODR.ODR_MONTH
		,ODR.ODR_SEQ
		,ODR.DLV_SUBMIT_DATE
		,ODR.DLV_DEADLINE_DATE
		,ODR.DLVREP_SUBMIT_DATE
		,ODR.CMPREP_ISSUE_DATE
		,ODR.CMPREP_DEADLINE_DATE
		,ODR.CMPMAIL_ISSUE_DATE
		,ODR.CMPMAIL_DEADLINE_DATE
		,ODR.CNST_MANAGER
		,STF.STAFF_NAME
		,ODR.[TYPE]
		,ODR.REV_ISSUE_DATE
		,ODR.REV_NO
		,ODR.EST_ISSUE_DATE
		,ODR.CUSTOMER_ID
		,CUS.CUSTOMER_NAME
		,ODR.ODR_NAME
		,ODR.CNST_START_DATE
		,ODR.CNST_END_DATE
		,ODR.OPEN_DATE
		,ODR.NOTE
		,SAL.ESTREQ_NO_1
		,SAL.ESTREQ_NO_2
		,SAL.PRODUCT_NO
		,SAL.REQ_DATE
		,SAL.REQ_NO
		,SAL.ODR_DATE
		,SAL.ODR_NO
		,SAL.ACCEPT_DATE
		,SAL.ACCEPT_MONTH
		,SAL.PAYMENT_MONTH
		,SAL.ANS_NET_PRICE
		,SAL.ANS_TAX_PRICE
GO


